scan:
  concurrency: 2
  timeout: 15
  follow_redirects: false
  max_depth: 2
  user_agent: "WebScanner-Safe/1.0"
  retries: 1

detection:
  passive: true
  active: false
  fuzzing: false
  headers: true
  cookies: true

logging:
  level: INFO
  file: "webscanner_safe.log"

report:
  output_dir: "reports/safe/"
  format: "json"
