xss:
  enabled: true
  types: ["reflected"]
sqli:
  enabled: true
  types: ["basic"]
ssrf:
  enabled: false
xxe:
  enabled: false
file_upload:
  enabled: false
auth_access:
  enabled: true
csrf:
  enabled: true

scan:
  concurrency: 10
  max_depth: 3
